docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: v1/intro.md
site_name: 'mezzio-httphandlerrunner-roadrunner'
site_description: ''
repo_url: 'https://github.com/mezzio/mezzio-httphandlerrunner-roadrunner'
